### PR TITLE
ADD options

### PR DESCRIPTION
**Pull request by ndelangen**
@SimenB would this be something you'd be looking for?

During serialization you can add options to choose which data types you want to ignore during serialization.

### CODE REVIEW

**Comment by ndelangen** [comment]
If this looks useful to you, all it needs is some tests added.

**Comment by ndelangen** [comment]
this resolves: https://github.com/storybooks/telejson/issues/2

**Comment by ndelangen** [comment]
Released as v2.2.0

**Comment by SimenB** [comment]
Awesome, thanks!

**Pull request merged**
